parameters:
  - name: module
    type: string
  - name: environment
    type: string
  - name: subscription
    type: string
  - name: dependsOnTfModules
    type: object
    default: []
  - name: variableGroupName
    type: string
    default: ''
  - name: runApply
    type: boolean
    default: false

jobs:
  - job: terragrunt_${{parameters.module}}_${{parameters.environment}}
    displayName: ${{parameters.environment}}-${{parameters.module}}-terragrunt
    variables:
      moduleDir: '$(System.DefaultWorkingDirectory)/environments/${{parameters.environment}}/${{parameters.module}}'
    ${{ if parameters.dependsOnTfModules }}:
      dependsOn:
        - ${{ each module in parameters.dependsOnTfModules }}:
            - terragrunt_${{ module }}_${{parameters.environment}}

    steps:
      - bash: |
          wget https://github.com/gruntwork-io/terragrunt/releases/latest/download/terragrunt_linux_amd64
          mv terragrunt_linux_amd64 terragrunt
          chmod +x terragrunt
          sudo mv terragrunt /usr/local/bin
          sudo apt-get install zip -y
        displayName: Install Terragrunt and Tools

      - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
        displayName: Install Terraform
        inputs:
          terraformVersion: '1.11.4'

      - task: Bash@3
        displayName: 'Install Azure CLI'
        inputs:
          filePath: '$(System.DefaultWorkingDirectory)/pipeline/scripts/install_cli.sh'

      - task: AzureCLI@2
        displayName: Authenticate Terraform
        inputs:
          scriptType: bash
          scriptLocation: inlineScript
          azureSubscription: ${{parameters.subscription}}
          addSpnToEnvironment: true
          inlineScript: |
            echo "##vso[task.setvariable variable=ARM_SUBSCRIPTION_ID]$(az account show --query id --output tsv)"
            echo "##vso[task.setvariable variable=ARM_CLIENT_ID]$servicePrincipalId"
            echo "##vso[task.setvariable variable=ARM_CLIENT_SECRET]$servicePrincipalKey"
            echo "##vso[task.setvariable variable=ARM_TENANT_ID]$tenantId"

      - bash: |
          # Ensure jq
          if ! command -v jq &> /dev/null; then
            echo "Installing jq..."
            sudo apt update
            sudo apt install -y jq
          fi

          echo "Configuring az devops cli..."
          az devops configure --defaults organization='$(System.TeamFoundationCollectionUri)' project='$(System.TeamProject)' --use-git-aliases true

          echo "Retrieving variables from variable group ${{ parameters.variableGroupName }}..."

          # Get variable group id
          variableGroupId="$(az pipelines variable-group list --group-name ${{ parameters.variableGroupName }} --query [].id -o tsv)"

          VARS_FILE=terraform.tfvars.json
          echo "Writing variables to $VARS_FILE..."

          # Write all variables in the group to a file
          az pipelines variable-group variable list --group-id $variableGroupId > vars.json

          # Write tfvars file
          jq 'map_values(.value)' vars.json > "$VARS_FILE"

          if [ -f "$VARS_FILE" ]; then
            echo "File $VARS_FILE has been written to $(moduleDir). It will be automatically consumed by terraform."
            exit 0
          else
            echo "File $VARS_FILE not found."
            exit 1
          fi
        displayName: 'Write tfvars file from variable group'
        condition: ${{ ne(parameters.variableGroupName, '') }}
        workingDirectory: $(moduleDir)
        env:
          AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)

      - bash: |
          PLAN_PATH='$(moduleDir)/tf.plan'

          (terragrunt plan -out $PLAN_PATH --detailed-exitcode) || error_code=$?
          if [[ "${error_code}" -eq 1 ]]; then
            exit 1
          elif [[ "${error_code}" -eq 2 ]]; then
            echo "##vso[task.logissue type=warning]Plan '${{parameters.module}}' has changes on ${{parameters.environment}}"
          fi
        displayName: "!!!! ${{parameters.environment}} Plan ${{parameters.module}} !!!!"
        workingDirectory: $(moduleDir)

      - bash: |
          PLAN_PATH='$(moduleDir)/tf.plan'
          terragrunt apply $PLAN_PATH
        condition: ${{ eq(parameters.runApply, true) }}
        displayName: "!!! ${{parameters.environment}} Apply ${{parameters.module}} !!!"
        workingDirectory: $(moduleDir)

      - bash: |
          rm -f vars.json terraform.tfvars.json
        displayName: "Delete sensitive variable files"
        workingDirectory: $(moduleDir)
