---
trigger: none
pr: none

resources:
  pipelines:
    - pipeline: ComplexCasesBuild
      source: LaCC Application - Build
      trigger:
        branches:
          include:
            - refs/heads/main
        stages:
          - Publish_Artifacts

variables:
  - group: complex-cases-global
  - group: complex-cases-terraform

stages:
  #release to DEV
  - template: ../templates/template_deploy-to-environment.yml
    parameters:
      buildAgentName: $(build-agent-pre-prod)
      initialStageDependsOn:
      targetEnv: "LaCC_DEV"
      targetBuild: ComplexCasesBuild
      targetLabel: "DEV"
      targetLabelLower: "dev"
      azureSubscription: $(azure-subscription-pre-prod)
      targetPlanName: "dev"
      terraformStorageAccount: $(terraform-storage-name-dev)
      applicationTerraformContainerName: $(terraform-container-name-application-dev)
      terraformStateKey: $(terraform-state-file)
      terraformStateAccessKey: $(terraform-storage-shared-key-preprod)
      targetSuffix: "-dev"
      logRetentionTime: $(log-retention-time)
      totalLogRetentionTime: $(total-log-retention-time)
      sharedSuffix: "preprod"
      statusCheckMethod: $(status-check-method)
      statusCheckRetries: $(status-check-retries)
      statusCheckDelaySeconds: $(status-check-delay-seconds)
      statusCheckTimeoutSeconds: $(status-check-timeout-seconds)
      e2eTestsStageDependsOn: Check_Status_DEV
      e2eTestsBuildDefinitionId: 588

  #conditional and gates release to QA
  - template: ../templates/template_deploy-to-environment.yml
    parameters:
      buildAgentName: $(build-agent-pre-prod)
      #initialStageDependsOn: Run_e2e_Tests_DEV
      initialStageDependsOn: Check_Status_DEV
      targetEnv: "LaCC_QA"
      targetBuild: ComplexCasesBuild
      targetLabel: "QA"
      targetLabelLower: "qa"
      azureSubscription: $(azure-subscription-pre-prod)
      targetPlanName: "qa"
      terraformStorageAccount: $(terraform-storage-name-qa)
      applicationTerraformContainerName: $(terraform-container-name-application-qa)
      terraformStateKey: $(terraform-state-file)
      terraformStateAccessKey: $(terraform-storage-shared-key-preprod)
      targetSuffix: "-qa"
      logRetentionTime: $(log-retention-time)
      totalLogRetentionTime: $(total-log-retention-time)
      sharedSuffix: "preprod"
      statusCheckMethod: $(status-check-method)
      statusCheckRetries: $(status-check-retries)
      statusCheckDelaySeconds: $(status-check-delay-seconds)
      statusCheckTimeoutSeconds: $(status-check-timeout-seconds)
      e2eTestsStageDependsOn: Check_Status_QA
      e2eTestsBuildDefinitionId: 588
