---
trigger: none
pr: none

resources:
  pipelines:
    - pipeline: ComplexCasesBuild
      source: LaCC Application - Test - Build
      trigger:
        branches:
          include:
            - refs/heads/main
        stages:
          - Publish_Artifacts

variables:
  - group: complex-cases-global
  - group: complex-cases-terraform

stages:
  #release to E2E
  - template: ../templates/template_deploy-to-environment.yml
    parameters:
      buildAgentName: $(build-agent-pre-prod)
      initialStageDependsOn:
      targetEnv: "LaCC_TEST"
      targetBuild: ComplexCasesBuild
      targetLabel: "TEST"
      azureSubscription: $(azure-subscription-pre-prod)
      targetPlanName: "test"
      terraformStorageAccount: $(terraform-storage-name-test)
      applicationTerraformContainerName: $(terraform-container-name-application-test)
      terraformStateKey: $(terraform-state-file)
      terraformStateAccessKey: $(terraform-storage-shared-key-preprod)
      targetSuffix: "-test"
      logRetentionTime: $(log-retention-time)
      totalLogRetentionTime: $(total-log-retention-time)
      sharedSuffix: "preprod"
      statusCheckMethod: $(status-check-method)
      statusCheckRetries: $(status-check-retries)
      statusCheckDelaySeconds: $(status-check-delay-seconds)
      statusCheckTimeoutSeconds: $(status-check-timeout-seconds)
      e2eTestsStageDependsOn: Update_GitHub_Tag_TEST
      e2eTestsBuildDefinitionId: 588
