---
trigger: none

pr:
  branches:
    include:
      - main
  paths:
    include:
      - terraform/networking/*
        
variables:
  - group: complex-cases-global
  - group: complex-cases-terraform
  - name: buildConfiguration
    value: "Release"
  - name: terraformWorkingDir
    value: "$(System.DefaultWorkingDirectory)/terraform/networking"
    
pool:
  name: $(build-agent-pre-prod)
    
stages:
  - stage: Validate
    displayName: Validate Changes
    jobs:
      - job: Validate_Networking_Terraform
        steps:
          - template: ../templates/stages/jobs/tasks/task_get-credentials.yml
            parameters:
              azureSubscription: $(azure-subscription-pre-prod)
            
          - task: JasonBJohnson.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller@1
            displayName: Terraform > Install
            inputs:
              terraformVersion: latest
              
          # Terraform Init
          - bash: |
              terraform init \
                -backend-config="storage_account_name=$TF_STATE_ACCOUNT_NAME" \
                -backend-config="container_name=$TF_STATE_CONTAINER_NAME" \
                -backend-config="key=$TF_STATE_KEY" \
                -backend-config="access_key=$TF_STATE_ACCESS_KEY"
            displayName: Terraform > Init
            workingDirectory: $(terraformWorkingDir)
            env:
              TF_STATE_ACCOUNT_NAME: $(terraform-storage-name-preprod)
              TF_STATE_CONTAINER_NAME: $(terraform-container-name-networking-preprod)
              TF_STATE_KEY: $(terraform-state-file)
              TF_STATE_ACCESS_KEY: $(terraform-storage-shared-key-preprod)
              TF_LOG: $(log-level-preprod)
    
          # Validate
          - bash: terraform validate
            displayName: Terraform > Validate Config
            workingDirectory: $(terraformWorkingDir)
    
      - job: Check_Networking_Plan
        dependsOn: Validate_Networking_Terraform
        condition: succeeded()
        displayName: Check Networking Terraform
        steps:
          - template: ../templates/stages/jobs/tasks/task_get-credentials.yml
            parameters:
              azureSubscription: $(azure-subscription-pre-prod)
              
          # Terraform Init
          - task: JasonBJohnson.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller@1
            displayName: Terraform > Install
            inputs:
              terraformVersion: latest

          - bash: |
              terraform init \
                -backend-config="storage_account_name=$TF_STATE_ACCOUNT_NAME" \
                -backend-config="container_name=$TF_STATE_CONTAINER_NAME" \
                -backend-config="key=$TF_STATE_KEY" \
                -backend-config="access_key=$TF_STATE_ACCESS_KEY"
            displayName: Terraform > Init
            workingDirectory: $(terraformWorkingDir)
            env:
              TF_STATE_ACCOUNT_NAME: $(terraform-storage-name-preprod)
              TF_STATE_CONTAINER_NAME: $(terraform-container-name-networking-preprod)
              TF_STATE_KEY: $(terraform-state-file)
              TF_STATE_ACCESS_KEY: $(terraform-storage-shared-key-preprod)
              TF_LOG: $(log-level-preprod)
    
          # Terraform Plan
          - bash: |
              terraform plan -input=false -out=preprod.tfplan -var-file="preprod.tfvars"
            displayName: 'Terraform > Write Networking Plan'
            workingDirectory: $(terraformWorkingDir)
            env:
              ARM_CLIENT_ID: $(clientId)
              ARM_CLIENT_SECRET: $(clientSecret)
              ARM_TENANT_ID: $(tenantId)
              ARM_SUBSCRIPTION_ID: $(subscriptionId)
              TF_LOG: $(log-level-preprod)
