---
trigger: none
pr: none

resources:
  pipelines:
    - pipeline: ComplexCasesNetworkingBuild
      source: LaCC Networking - Build
      trigger:
        branches:
          include:
            - refs/heads/main
        stages:
          - Publish_Artifacts
            
variables:
  - group: complex-cases-global
  - group: complex-cases-terraform
    
pool:
  name: $(build-agent-pre-prod)

stages:
  - stage: Apply_PREPROD
    displayName: PREPROD > Apply Terraform
    jobs:
      - deployment: Apply_PREPROD_Networking_Terraform
        environment: "LaCC_PREPROD"
        workspace:
          clean: all
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/stages/jobs/tasks/task_get-credentials.yml
                  parameters:
                    azureSubscription: $(azure-subscription-pre-prod)
                    
                - template: ../templates/stages/jobs/tasks/task_apply-terraform.yml
                  parameters:
                    targetBuild: ComplexCasesNetworkingBuild
                    targetTerraformArtifact: "terraform-files-networking"
                    targetLabel: "PREPROD"
                    targetName: "Networking Terraform CI Deployment"
                    targetPlanName: "preprod"
                    terraformStorageAccount: $(terraform-storage-name-preprod)
                    terraformContainerName: $(terraform-container-name-networking-preprod)
                    terraformStateKey: $(terraform-state-file)
                    terraformStateAccessKey: $(terraform-storage-shared-key-preprod)
                    armClientId: $(clientId)
                    armClientSecret: $(clientSecret)
                    armTenantId: $(tenantId)
                    armSubscriptionId: $(subscriptionId)
                    
  # Apply to PROD              
  # - stage: Apply_PROD
  #   displayName: PROD > Apply Terraform
  #   dependsOn: Apply_PREPROD
  #   condition: succeeded()
  #   jobs:
  #     - deployment: Apply_PROD_Networking_Terraform
  #       environment: "LaCC_PROD"
  #       workspace:
  #         clean: all
  #       strategy:
  #         runOnce:
  #           deploy:
  #             steps:
  #               - template: ../templates/stages/jobs/tasks/task_get-credentials.yml
  #                 parameters:
  #                   azureSubscription: $(azure-subscription-prod)
                    
  #               - template: ../templates/stages/jobs/tasks/task_apply-terraform.yml
  #                 parameters:
  #                   targetBuild: ComplexCasesNetworkingBuild
  #                   targetTerraformArtifact: "terraform-files-networking"
  #                   targetLabel: "PROD"
  #                   targetName: "Networking Terraform CI Deployment"
  #                   targetPlanName: "prod"
  #                   terraformStorageAccount: $(terraform-storage-name-prod)
  #                   terraformContainerName: $(terraform-container-name-networking-prod)
  #                   terraformStateKey: $(terraform-state-file)
  #                   terraformStateAccessKey: $(terraform-storage-shared-key-prod)
  #                   armClientId: $(clientId)
  #                   armClientSecret: $(clientSecret)
  #                   armTenantId: $(tenantId)
  #                   armSubscriptionId: $(subscriptionId)
