trigger:
  batch: true
  branches:
    include:
      - main

pr: none

variables:
  - group: lacc-deployment-global

pool: 'LaCC PreProd Pool'

steps:
  - checkout: self
    persistCredentials: true

  - script: |
      gitTag="v$(releaseVersion)"
      remoteTag="refs/tags/$gitTag"

      latestTag=$(git ls-remote "$(Build.Repository.Uri)" -t | awk '{print $2}')

      echo "Latest existing tag: $latestTag"
      echo "Tag to push: $remoteTag"

      # if [ "$remoteTag" = "$latestTag" ]; then
      #   echo "##vso[task.logissue type=warning]The repository already has a tag for version $gitTag."
      # else
      #   echo "Tag $gitTag does not exist in this repository. Tagging..."
      #   git tag $gitTag
      #   git push origin $remoteTag
      # fi
    displayName: "Tag repo"
