---
trigger:
  branches:
    include:
      - 'main'

pool: 'LARGE-AND-COMPLEX-CASES-PRE-POD' #'LaCC Pre-Prod Build Agents'

jobs:
  - template: templates/terragrunt_apply.yml
    parameters:
      environment: applications
      module: base
      subscription: "Azure Pipeline: Large and Complex Cases - Pre-Prod" #service principal
      backend_storage_resource_group: "rg-lacc-tf"
      backend_storage_account_name: "salacctfstatedev"
      application_name: "applications"
