---
trigger:
  branches:
    exclude:
      - main

pool: 'LaCC Pre-Prod Build Agents'  #'LARGE-AND-COMPLEX-CASES-PRE-POD'

jobs:
  - template: templates/terragrunt_plan.yml
    parameters:
      environment: dev
      module: applications
      subscription: "Azure Pipeline: Large and Complex Cases - Pre-Prod" #service principal
      backend_storage_resource_group: "rg-lacc-devops
      backend_storage_account_name: "salacctfstatedev"
      application_name: "applications"
