---
trigger:
  branches:
    include:
    - 'main'
  paths:
    include:
    - environments/dev

pr: none

pool: 'LaCC PreProd Pool'

jobs:
  - template: templates/terragrunt_job.yml
    parameters:
      environment: dev
      module: applications
      subscription: "Azure Pipeline: Large and Complex Cases - Pre-Prod" #service principal
      runApply: true

  - template: templates/terragrunt_job.yml
    parameters:
      environment: dev
      module: base
      subscription: "Azure Pipeline: Large and Complex Cases - Pre-Prod" #service principal
      runApply: true
