---
trigger:
  branches:
    include:
    - 'main'
  paths:
    include:
    - environments/prod

pr: none

stages:
- stage: apply_applications
  variables:
  - group: lacc-infra-validation-prod
  jobs:
  - template: templates/terragrunt_execute_job.yml
    parameters:
      environment: prod
      module: applications
      subscription: "Azure Pipeline: Large and Complex Cases - Prod" #service principal
      agentPool: 'LaCC Prod Pool'
      runApply: true

- stage: apply_base
  variables:
  - group: lacc-infra-validation-prod
  jobs:
  - template: templates/terragrunt_execute_job.yml
    parameters:
      environment: prod
      module: base
      subscription: "Azure Pipeline: Large and Complex Cases - Prod" #service principal
      agentPool: 'LaCC Prod Pool'
      runApply: true
