---
trigger:
  branches:
    include:
    - 'main'
  paths:
    include:
    - environments/dev

pr: none

pool: 'LaCC PreProd Pool'

jobs:
  - template: templates/terragrunt_apply.yml
    parameters:
      environment: dev
      module: applications
      subscription: "Azure Pipeline: Large and Complex Cases - Pre-Prod" #service principal
      backend_storage_resource_group: "rg-lacc-devops"
      backend_storage_account_name: "salacctfstatedev"
      application_name: "applications"

  - template: templates/terragrunt_apply.yml
    parameters:
      environment: dev
      module: base
      subscription: "Azure Pipeline: Large and Complex Cases - Pre-Prod" #service principal
      backend_storage_resource_group: "rg-lacc-devops"
      backend_storage_account_name: "salacctfstatedev"
      application_name: "base"
