---
trigger:
  branches:
    include:
    - 'main'
  paths:
    include:
    - environments/prod

pr: none

jobs:
  - template: templates/terragrunt_execute_job.yml
    parameters:
      environment: prod
      module: applications
      subscription: "Azure Pipeline: Large and Complex Cases - Prod" #service principal
      agentPool: 'LaCC Prod Pool'
      runApply: true
      approvalVariableGroupName:

  - template: templates/terragrunt_execute_job.yml
    parameters:
      environment: prod
      module: base
      subscription: "Azure Pipeline: Large and Complex Cases - Prod" #service principal
      agentPool: 'LaCC Prod Pool'
      runApply: true
      approvalVariableGroupName: 'lacc-infra-approval-prod'
