---
trigger:
  branches:
    include:
    - 'main'
  paths:
    include:
    - environments/prod

pr: none

pool: 'LaCC Prod Pool'

jobs:
  - template: templates/terragrunt_job.yml
    parameters:
      environment: prod
      module: applications
      subscription: "Azure Pipeline: Large and Complex Cases - Prod" #service principal
      runApply: true

  - template: templates/terragrunt_job.yml
    parameters:
      environment: prod
      module: base
      subscription: "Azure Pipeline: Large and Complex Cases - Prod" #service principal
      runApply: true
