---
trigger:
  branches:
    exclude:
    - main
  # The following is set manually via the ADO UI as it isn't working for a yet unknown reason
  # paths:
  #   include:
  #   - environments/dev

pr: none

pool: 'LACC PreProd Pool'

jobs:
  - template: templates/terragrunt_job.yml
    parameters:
      environment: dev
      module: applications
      subscription: "Azure Pipeline: Large and Complex Cases - Pre-Prod" #service principal

  - template: templates/terragrunt_job.yml
    parameters:
      environment: dev
      module: base
      subscription: "Azure Pipeline: Large and Complex Cases - Pre-Prod" #service principal
