---
trigger:
  branches:
    exclude:
    - main
  # The following is set manually via the ADO UI as it isn't working for a yet unknown reason
  # paths:
  #   include:
  #   - environments/prod

pr: none

jobs:
  - template: templates/terragrunt_job.yml
    parameters:
      environment: prod
      module: applications
      subscription: "Azure Pipeline: Large and Complex Cases - Prod" #service principal
      agentPool: 'LaCC Prod Pool'

  - template: templates/terragrunt_job.yml
    parameters:
      environment: prod
      module: base
      subscription: "Azure Pipeline: Large and Complex Cases - Prod" #service principal
      agentPool: 'LaCC Prod Pool'
