---
trigger:
  branches:
    exclude:
    - main
  # The following is set manually via the ADO UI as it isn't working for a yet unknown reason
  # paths:
  #   include:
  #   - environments/staging

pr: none

pool: 'LaCC PreProd Pool'

jobs:
  - template: templates/terragrunt_job.yml
    parameters:
      environment: staging
      module: applications
      subscription: "Azure Pipeline: Large and Complex Cases - Pre-Prod" #service principal
      variableGroupName: 'lacc-infra-vars-staging'

  - template: templates/terragrunt_job.yml
    parameters:
      environment: staging
      module: base
      subscription: "Azure Pipeline: Large and Complex Cases - Pre-Prod" #service principal
