---

steps:
  - bash: |
      echo '==== Update package sources ===='
      until sudo apt-get -yq update
      do
      echo "Try again"
      sleep 2
      done
      
      echo '==== PowerShell ===='
      sudo snap install powershell --classic
    displayName: Install PowerShell