---
parameters:
  - name: targetBuild
    type: string
  - name: targetLabel
    type: string
  - name: targetName
    type: string
  - name: targetSuffix
    type: string
  - name: azureSubscription
    type: string

steps:
  # download scripts artifact
  - download: ${{ parameters.targetBuild }}
    displayName: Download Scripts
    artifact: 'complex-cases-script-files'

  # download text-extractor build artifact
  - download: ${{ parameters.targetBuild }}
    displayName: Deploy > Download API Build
    artifact: "complex-cases-api-drop"

  # Deploy Related Codebase to Env
  - task: AzureFunctionApp@2
    displayName: 'Deploy API as an Azure Function App to ${{ parameters.targetLabel }}'
    inputs:
      azureSubscription: ${{ parameters.azureSubscription }}
      appType: functionAppLinux
      appName: "lacc${{ parameters.targetSuffix }}-api"
      package: $(Pipeline.Workspace)/${{ parameters.targetBuild }}/complex-cases-api-drop
      runtimeStack: "DOTNET-ISOLATED|8.0"
      resourceGroupName: "rg-LaCC${{ parameters.targetSuffix }}-application"
      deploymentMethod: "runFromPackage"
