---
parameters:
  - name: targetBuild
    type: string
  - name: azureSubscription
    type: string
  - name: targetSuffix
    type: string
  - name: statusCheckRetries
    type: string
  - name: statusCheckDelaySeconds
    type: string
  - name: statusCheckTimeoutSeconds
    type: string
  
steps:
  # download Mock Service codebase build artifact
  - download: ${{ parameters.targetBuild }}
    displayName: Download Mock Service Codebase Build
    artifact: "mock-service-drop"
  
  # download scripts artifact
  - download: ${{ parameters.targetBuild }}
    displayName: Download Scripts
    artifact: "complex-cases-script-files"

  - template: task_get-credentials.yml
    parameters:
      azureSubscription: ${{ parameters.azureSubscription }}
      
  - template: dependencies/task_install-powershell.yml
  
  # Deploy Mock Service Codebase to Env
  - task: AzureRmWebAppDeployment@4
    displayName: "Deploy Mock App Service"
    inputs:
      azureSubscription: ${{ parameters.azureSubscription }}
      appType: webAppLinux
      WebAppName: "lacc${{ parameters.targetSuffix }}-mock"
      packageForLinux: $(Pipeline.Workspace)/${{ parameters.targetBuild }}/mock-service-drop
      enableCustomDeployment: true
      RemoveAdditionalFilesFlag: true
