---
parameters:
  - name: azureSubscription
    type: string
    
steps:
  - template: dependencies/task_install-zip-utilities.yml

  - template: dependencies/task_install-az-cli.yml
    
  - task: AzureCLI@2
    displayName: Fetch Azure Credentials
    name: credentials
    inputs:
      azureSubscription: ${{ parameters.azureSubscription }}
      scriptType: bash
      addSpnToEnvironment: true # this will add the required credentials to env vars
      useGlobalConfig: true
      scriptLocation: inlineScript
      inlineScript: |
        echo "##vso[task.setvariable variable=tenantId;]$tenantId"
        echo "##vso[task.setvariable variable=clientId;]$servicePrincipalId"
        echo "##vso[task.setvariable variable=clientSecret;]$servicePrincipalKey"
        echo "##vso[task.setvariable variable=subscriptionId;]$(az account show --query="id" -o tsv)"