---
parameters:
  - name: targetBuild
    type: string
  - name: targetLabel
    type: string
  - name: targetName
    type: string
  - name: targetSuffix
    type: string
  - name: azureSubscription
    type: string

steps:
  # download scripts artifact
  - download: ${{ parameters.targetBuild }}
    displayName: Download Scripts
    artifact: 'complex-cases-script-files'

  # download UI build artifact
  - download: ${{ parameters.targetBuild }}
    displayName: Deploy > Download UI Build
    artifact: "ui-spa-drop"

  # Deploy Related Codebase to Env
  - task: AzureRmWebAppDeployment@4
    displayName: 'Deploy UI as an App Service to ${{ parameters.targetLabel }}'
    inputs:
      azureSubscription: ${{ parameters.azureSubscription }}
      appType: webAppLinux
      WebAppName: "LaCC${{ parameters.targetSuffix }}-ui"
      packageForLinux: $(Pipeline.Workspace)/${{ parameters.targetBuild }}/ui-spa-drop
      resourceGroupName: "rg-LaCC${{ parameters.targetSuffix }}-application"
