parameters:
  - name: buildAgentName
    type: string
  - name: targetBuild
    type: string
  - name: targetLabel
    type: string
  - name: buildDefinitionId
    type: string
  - name: stageDependsOn
    type: object

stages:
  - stage: Run_e2e_Tests_${{ parameters.targetLabel }}
    pool:
      name: ${{ parameters.buildAgentName }}
    displayName: ${{ parameters.targetLabel }} > Run e2e Tests
    dependsOn: ${{ parameters.stageDependsOn }}
    condition: succeeded()
    jobs:
      - job: Run_e2e_Tests
        condition: succeeded()
        steps:
          - template: jobs/tasks/task_run-e2e-tests.yml
            parameters:
              targetLabel: ${{ parameters.targetLabel }}
              buildDefinitionId: ${{ parameters.buildDefinitionId }}
              devOpsPatToken: $(System.AccessToken)
